### PR TITLE
Add fullBackupContent to Sample Android Manifest

### PR DESCRIPTION
**Pull request by vanniktech**

### CODE REVIEW

**Comment by dlew** [comment]
...Does this really matter? It's a sample.

**Comment by vanniktech** [comment]
Not really I'd assume it's just a cosmetic change

**Comment by dlew** [comment]
Eh, whatever. Doesn't hurt, probably avoids a lint check.

**Comment by vanniktech** [comment]
@dlew yes it avoids a lint check

**Pull request merged**
