### PR TITLE
Add RxPreferenceFragmentCompat component

### PR DESCRIPTION
**Pull request by pawegio**
`PreferenceFragmentCompat` returns to grace with new android support library, since it's necessary if we want to use `PreferenceDataStore` below API level 26.

### CODE REVIEW

**Comment by dlew** [comment]
On the one hand: yes, this makes a lot of sense.

On the other hand, I don't want to add another transitive dependency for people who don't need it.

Thoughts?

**Comment by vanniktech** [comment]
The extra dependency is really unfortunate.

**Comment by pawegio** [comment]
Ok, I agree with both of you. What do you think about extracting it to another module, e.g. `rxlifecycle-components-preference`? I believe that it is reasonable since [preference-v7](https://developer.android.com/reference/android/support/v7/preference/package-summary.html) package comes with multiple fragments targeting different use cases such as:
- `PreferenceFragmentCompat` (already added in this PR)
- `EditTextPreferenceDialogFragmentCompat`
- `PreferenceDialogFragmentCompat`
- `ListPreferenceDialogFragmentCompat`
Since I am currently experimenting with preference data stores I can handle it.

**Comment by dlew** [comment]
Yeah. I think if we want to add this, it should be in its own dependency. It's more of a pain to setup initially but it saves a lot of headache for consumers.

It's how we should've done the original split between OS and support components, too. We could still go back and do it that way, in fact...

**Comment by pawegio** [comment]
Now it is extracted to its own dependency.

**Comment by dlew** [comment]
This is great, thanks!

**Comment by dlew** [comment]
I've pushed out v2.2.0 which includes this new artifact.

**Pull request merged**
