### PR TITLE
RxLifecycle Lint Check

### PR DESCRIPTION
**Pull request by nick-fedesna**
Adds a lint check to the RxLifecycle library which ensures you are binding your subscription in places where it's important (things in the `app`, `view` and `widget` packages).  The lint check analyzes .class files (so it's working with Kotlin too) looking for `.subscribe()` methods and walking backwards for any of the `compose(bind___())` methods (or the Kotlin extensions `.bind___()`.  

If no `bind` method is found it reports an error.  I chose to default to error but that could be relaxed via `lintOptions` or of course ignored on a case-by-case basis via `@SuppressLint` annotation. If you would prefer to default to warning, that is okay too.

As for packaging (from what I gathered from limited info on the web) this bundles a `lint.jar` with the RxLifecycle `.aar`.  That JAR is then picked up by Lint when run on the project.  I've tested using a SNAPSHOT here and it is working automatically.

NOTE: This is my first foray into Lint checks, so I'm open to constructive criticism.

### CODE REVIEW

**Comment by dlew** [comment]
Does this actually need to be part of the rxlifecycle project, or could it be its own separate project?

The reason I ask is because I'm not particularly interested in maintaining such a lint check, so I'm afraid of this aspect of the code going stale.

**Comment by nick-fedesna** [comment]
We feel it does belong in RxLifecycle proper since you get the check for free without the need to add an additional dependency. If it were in a separate project it wouldn't benefit as many people as I don't think many would add the extra dependency only for a lint check.  Not to mention the fact that they'd have to be aware of it's existence in the first place.

**Comment by dlew** [comment]
The popularity of the lint check is not a high priority for this project. Much higher up is quality and maintainability, which I think will be better served by this lint check being in its own separate lib with its own maintainers, instead of adding more to the workload for RxLifecycle.

We can certainly link to it in the README from here, though.

**Comment by nick-fedesna** [comment]
Fair enough, I'll get this going in it's own repo and let you know when there is something to link to.

**Comment by nick-fedesna** [comment]
@dlew we have the lint check published: `compile 'io.vokal.lint:rxlifecycle:1.0.0'`
The repository is here: https://github.com/vokal/Android-Lint-Checks

**Comment by dlew** [comment]
Awesome. I'll put a reference to it in the README.

**Comment by nick-fedesna** [comment]
Thanks @dlew!

**Pull request closed without merging**
